language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: S9npjr92YNAd06yPSztypR1hlT+reG2vGjb/Wtz072NT3MWbhjwYBRKsRIYICXwyETPRbUTPSwsqQ82rRRdlNOp2Vcc7s+9eIsznLILJov3NYjHY/vREk5p83fRxo3xifHHt8j7ANCKAZa7lUBc7mfEfsgh64PPy+ypPRV0A83q0fqWjyDd1jbNjO9q9XaIEP9l+SqLpOxqQayJc+TdnpUH1wJ4Sw+OtreIQF6oT77dizkrVswLe55eCDdbCthjcBwdWEtLpjiZXfIbStG64svWODJZ0NmHoephRByd6gydWazacK79q9MidqYoq5tRKx3u5qV588HBv0bAJzOOaTlxbYGm5GuzOPBcVFpFXgTjePKEA3xf3uAZa/gRBbefNxCM9P6CZXWUqu0xlY+JDVTfJtFxtjq90ZYxzwICZfQ6oCg8JzInL+NDIHmQXBKFnlVE4g+NF1s5tI44aH4HeZgVGcfcm0ttHj0/fkD/Iuy1TfHjfLEvjOf13vxqAy9W9mZZkGiUSW1F/KVNfDJcJpt6TD+SUGILgZn3uoPvau8pfhnEb6ggM/EVoGJ5CqV5ipzM4/eww9nZn/NSWQBRcJG4fsnhc5k3rcPbhT3Pql2U9FKwDpFr8h/1Bf5J37uNRNWUkBrOhsHMeTWYMrQ+ynT9yuQQun/I6SUnVTNRiLDI=
  app: learnlo
  skip_cleanup: true
  all_branches: true